version: '3.8'

services:
  pytorch_cuda_test:
    build: .
    command: python check_cuda.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
